services:
  frontend:
    container_name: brands-web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${WEB_EXTERNAL_PORT:-5000}:5000"
    restart: unless-stopped
    tty: true

  backend:
    container_name: brands-api
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/project/src
      - ./migrations:/project/migrations
    depends_on:
      - db
      - redis
    ports:
      - "${API_EXTERNAL_PORT:-8000}:8000"
    restart: unless-stopped
    tty: true

  db:
    container_name: brands-db
    image: postgres:16-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${DB_EXTERNAL_PORT:-5432}:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-test}
    restart: unless-stopped
    tty: true

  redis:
    container_name: brands-redis
    image: redis:latest
    volumes:
      - cache:/data
    ports:
      - "${REDIS_EXTERNAL_PORT:-6379}:6379"
    restart: unless-stopped
    tty: true

volumes:
  postgres_data: { }
  cache: { }